<div class="alert alert-info">

# PSY 4016-G-H20
# Cueillette et traitement des données en neurosciences cognitives
## Chapitre 2: les structures de données, intro
<p>
<li> Structures de données:
    <ul>
        <li>la chaîne
        <li>l'entier
        <li>la flotte
        <li>la liste
        <li>le tuple
        <li>le dictionnaire
        <li>Pandas DataFrame
        <li>Numpy</ul>

<li> Les styles d'écriture de code python
<li> Indexation des structures de données
<li> Le Pseudo-code

#### commandes pour l'installation dans le terminal:

pip3 install pandas

pip3 install numpy

In [8]:
import pandas #as pd
import numpy as np

print('pandas version is: ', pandas.__version__)
print('numpy version is: ', np.__version__)

pandas version is:  1.4.4
numpy version is:  1.21.5


<div class="alert alert-info">
<h3>Les structures de données</h3>
</div>

<div class="alert alert-success">
<br>
<li>Les chaînes de caractères (texte) en python sont entourés de guillemets simples ou de guillemets doubles.
<li>les entiers sont des nombres
<li>les flottantes sont des nombres avec une valeur après la virgule
<li>la liste est une séquance de variables
<li>le tuple est une séquance de variables NON modifiable
<li>le dictionnaire est une structure avec de clés et de valeurs. Le dictionnaire N’EST pas une sequence
<p><p>
<li>les listes, tuples, dictionnaires, DataFrames sont hétérogènes et peuvent contenir:<ul>
    <li> des chaînes de caractères (strings)
    <li>des entiers
    <li>des objets</ul>
</div>

<div class="alert alert-success">

### comment créer une structure de données :

### chaîne:
    str()
    variable1 = str("variable")

### entiere:
    int()
    entiere1 = int(1)

### flottante:
    float()
    flottante1 = float(1)

### list - structure entre crochets:
    list()
    list1 = list()
    list1 =[]

### tuple - structure entre parenthèses:
    tuple()
    tuple1 = tuple()
    tuple1 = ()

### dictionnaire - structure entre accolades:
    dict()
    dictionnaire1 = dict()
    dictionnaire1 = {}

### pandas DataFrame:
    pandas.DataFrame()
    df1 = pandas.DataFrame()

</div>

<div class="alert alert-success">
    
## commandes python
    
#### pour vérifier le type de variable, utilisez la commande :
    
    type()
    
#### pour vérifier le type de variable, utilisez la commande :
    
    len()
</div>

In [9]:
# créer une chaîne

a = str("bonjour") #Version 1
a = "bonjour" #Version 2

print(a)
type(a)

bonjour


str

In [10]:
len(a)

7

In [11]:
# Vous pouvez affecter une chaîne multiligne 
# à une variable en utilisant trois guillemets:

a = """Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua."""
print(a)

Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua.


In [12]:
len(a)

123

In [13]:
# créer une entier

i = 300
print(i)
type(i)

300


int

In [14]:
# exception:

len(i)

TypeError: object of type 'int' has no len()

In [15]:
# solution de contournement

len(str(i))

3

In [16]:
# créer une flottante

flottante1 = float(1)
print(flottante1)
type(flottante1)

1.0


float

In [17]:
# exception:

len(flottante1)

TypeError: object of type 'float' has no len()

In [18]:
# solution de contournement

len(str(flottante1))

3

In [19]:
# créer plusieurs variables:

text3, c, text4 = 'montreal', 4, '.ca'
print(text3, c, text4)

montreal 4 .ca


In [20]:
# créer une liste

ls1 = ['text1', 'b', 'text2', 'text', [], ()]

print(ls1)
type(ls1)

['text1', 'b', 'text2', 'text', [], ()]


list

In [21]:
len(ls1)

6

In [22]:
# créer un tuple

tup1 = ('text1', 'b', 'text2', 'text')
print(tup1)
type(tup1)

('text1', 'b', 'text2', 'text')


tuple

In [23]:
tup2 = 'test1', 'text3'
print(tup2)
type(tup2)

('test1', 'text3')


tuple

In [24]:
len(tup2)

2

<div class="alert alert-warning">

<li>les listes et le tuples sont des structures 1D
</div>

<center><img src="img/numpy_1x3x1.png"><center>

In [25]:
# créer un dictionnaire

d1 = {
    'cle1':'variable',
    'cle2':[],
    'cle3': [1,2,3],
    'cle4': ('a', 'b',)
    }
print(d1)
type(d1)

{'cle1': 'variable', 'cle2': [], 'cle3': [1, 2, 3], 'cle4': ('a', 'b')}


dict

In [26]:
tup1 = ('abcd')
for i in tup1:
    print(i)

a
b
c
d


In [27]:
tup1 = ('abcd',)
for i in tup1:
    print(i)

abcd


In [28]:
len(d1)

4

In [29]:
# créer un pandas DataFrame
import pandas

df = pandas.DataFrame()
print(df)
type(df)

Empty DataFrame
Columns: []
Index: []


pandas.core.frame.DataFrame

In [30]:
len(df)

0

<div class="alert alert-warning">

les pandas DataFrames peuvent être créés à partir de:
<li> fichiers (csv, excel, json, etc.)
<li>listes
<li>dictionnaires
    </div>

In [31]:
# pandas dataframes du liste:

ls1 = ['text1', 'b', 'text2', 'text']
df_du_ls = pandas.DataFrame(ls1)

print(df_du_ls)

       0
0  text1
1      b
2  text2
3   text


In [32]:
# pandas dataframes du dictionnaire:

data = {'col_1': [3, 2, 1, 0],
        'col_2': ['a', 'b', 'c', 'd']}

df_d = pandas.DataFrame.from_dict(data) # Version 1
print(df_d)

   col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d


In [33]:
df_dv2 = pandas.DataFrame(data) # Version 2
print(df_dv2)

   col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d


In [34]:
type(df_d)

pandas.core.frame.DataFrame

In [35]:
# par défault les collones de la cadre de données correspond aux clés
df_d

col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d

In [36]:
# pour changer la structure, le paramètre "orient" peut être utilisé

df_d = pandas.DataFrame.from_dict(data, orient = 'index')
df_d

0  1  2  3
col_1  3  2  1  0
col_2  a  b  c  d

In [37]:
# alternativement, la commande "transpose" peut être utilisée
# qui est similaire à Microsoft Excel et LibreOffice calc

df_d = pandas.DataFrame.from_dict(data)

print(df_d)
print("\n\n\n")
print(df_d.transpose())

   col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d




       0  1  2  3
col_1  3  2  1  0
col_2  a  b  c  d


In [38]:
df_d = pandas.DataFrame.from_dict(data)

print(df_d)
print(df_d.T)

   col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d
       0  1  2  3
col_1  3  2  1  0
col_2  a  b  c  d


In [39]:
# les noms des colonnes peuvent également
# être définis à l'intérieur de la commande d'exécution

df_d = pandas.DataFrame.from_dict(data, orient = 'index',
                                 columns = ['A','B','C','D'])
df_d

# pour plus d'info:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

A  B  C  D
col_1  3  2  1  0
col_2  a  b  c  d

<div class="alert alert-warning">

<li>le dictionnaire et pandas DataFrame sont des structures 2D: multiple listes/ tuples 1D
</div>

<center><img src="img/numpy_5x5x1.png"><center>

<div class="alert alert-warning">

<li>les données 3D = multiple 2D sur plusieurs feuilles Excel
</div>

<center><img src="img/numpy_5x5x3.png"><center>

<div class="alert alert-warning">

<li>données 4D =<ul>
    <li>1 dossier avec
    <li>multiple fichiers Excel (3D)
    <li>avec multiple feuilles (2D)</ul>
</div>

<div class="alert alert-warning">

<li>données 5D =<ul>
    <li>multiple dossiers avec
    <li>multiple fichiers Excel (3D)
    <li>avec multiple feuilles (2D)</ul>
</div>

<div class="alert alert-warning">
Comment créer une structure 3/4/5D en python?</div>

<div class="alert alert-success">
<h2>NumPy = Numerical Python</h2>
</div>

<div class="alert alert-success">
<b>pourquoi NumPy est-il nécessaire ?</b>
<ul> 
    <li> Les variables en python sont flexibles, mais le coût est une manipulation moins efficace des données.
    <li> numpy est de type fixe, ils manquent de flexibilité mais ils est beaucoup plus efficaces pour stocker et manipuler des données.</ul>

<li> Auteur original Travis Oliphant, première version 1995, dernière 6 janvier 2020
<li> Repository: ithub.com/numpy/numpy
<li> Ref: https://www.nature.com/articles/s41586-020-2649-2</div>

<div class="alert alert-success">
<ul> <b>Avantages contre MATLAB</b>
    <li> Matlab fonctionne avec un grand nombre de boîtes à outils supplémentaires qui doivent être achetées. En Python, numpy est intégré ainsi qu'avec des packages python gratuits complémentaires comme SciPy 
    <li> MATLAB est un logiciel propriétaire à source fermée. Un code dans MATLAB, ne peut être utilisé que par des personnes qui peuvent se permettre une licence pour l'exécuter. Python est un logiciel gratuit et open-source. Non seulement vous pouvez télécharger Python gratuitement, mais vous pouvez également télécharger, consulter et modifier le code source. Le code Python pourrait être partagé et exécuté par tout lecteur intéressé.
    <li> Le langage MATLAB est développé exclusivement par Mathworks. Si Mathworks devait cesser ses activités, MATLAB ne pourrait plus être développé et pourrait éventuellement cesser de fonctionner. Les parties sensibles aux performances de NumPy sont toutes écrites en langage C, donc elles sont <b>très rapides.</b></ul>
    <p>
<ul> <b>Limites</b>
    <li> insérer / ajouter n'est pas aussi simple que pour les listes
    <li> la concaténation ne lie pas les tableaux, mais en renvoie un nouveau
    <li> le remodelage n'est possible que si le nombre d'éléments ne change pas. Un pack de remplacement Blaze tente de surmonter ce problème
    <li> Les algorithmes qui ne sont pas exprimables en tant qu'opération vectorisée s'exécuteront généralement lentement, car ils sont implémentés en Python pur. Des compilations peuvent être utilisées pour éviter cela: scipy.weabe, numexpr, Numba, Cython</ul></div>

<div class="alert alert-warning">
crée une structure numpy
<li><b>principe fondamental de NumPy = tableaux multi-dimensionnels</b>
    </div>

<div class="alert alert-warning">
<li>np.array
<li>np.empty
<li>np.zeros
<li>np.one
<li>np.full
<li>np.eye
<li>np.repeat
<li>np.linspace
<li>np.arange
<li>np.random
<li>np.random.random
<li>np.random.normal
<li>np.random.randint
</div>

In [40]:
import numpy as np

In [41]:
# Créer des tableaux de données
# entier
arr0 = np.array([1, 2, 3])
arr0

array([1, 2, 3])

In [42]:
arr0.shape

(3,)

In [43]:
# flottante
np.array([1.1, 2.2, 3.3]) # version 1

array([1.1, 2.2, 3.3])

In [44]:
# Les valeurs peuvent être spécifiées avec dtype:

np.array([1,2,3,4,5], dtype='float32')  # version 2

array([1., 2., 3., 4., 5.], dtype=float32)

In [45]:
# multidimensionnel

arr1 = np.array([[1, 2],
                 [3, 4]])
arr1

array([[1, 2],
       [3, 4]])

In [46]:
arr1.shape

(2, 2)

In [47]:
arr2 = np.array([[5, 6], [7, 8],[3, 5]])
arr2

array([[5, 6],
       [7, 8],
       [3, 5]])

In [48]:
# créer des tableaux vides:
# numpy.empty(shape, dtype, order)

# shape (allure) = dimensions du tableaux
# dtype = le typage attendu lors de son rendu (optionnel)
# order (ordre) = pour un tableaux style C (C) ou FORTRAN (F)

np.empty([3,3], dtype=int)

array([[ 4151192956528754769, -5067675480698650536,  4146689356901384305],
       [-5067675480698650536,  4160889769476436884, -5070236902986717532],
       [ 4146689356901384305, -5070236902986717532,  4149419664175477595]])

In [49]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [50]:
# Les valeurs peuvent être spécifiées avec dtype chaîne:

np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [51]:
# ou avec dtype objet:

np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [52]:
unes_tab = np.ones([2,2], dtype=float)
print(unes_tab)

[[1. 1.]
 [1. 1.]]


In [53]:
# faire un tableau 3x5 avec 3,14

np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [54]:
# créer une matrice d'identité
# avec de 1 par diagonale:

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
# répéter

np.repeat(1,10)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [56]:
# faire un tableau de 5 valeurs régulièrement espacées:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [57]:
# trancher

# x[début : arrêt : étape]
# x[start : stop : step]

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
# valeurs réparties équitablement
# numpy.arange(start, stop ,step, dtype)

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [60]:
np.arange(1,10,3)

array([1, 4, 7])

In [61]:
np.arange(1,10,2,float)

array([1., 3., 5., 7., 9.])

In [62]:
# random
# valeurs aléatoires uniformément réparties:

x2 = np.random.random((3,3))
x2

array([[0.19712603, 0.23871951, 0.79767091],
       [0.44678515, 0.88186695, 0.54679157],
       [0.86761684, 0.46066041, 0.34466736]])

In [63]:
# aléatoire normalement distribué avec moyenne 0 et std 1:
np.random.normal(0,1, (3,3))

array([[-1.41960316,  3.56824288, -0.84074958],
       [-0.3035835 , -0.06303084,  0.31303249],
       [ 1.12718532, -0.8771621 ,  0.64669627]])

In [64]:
# random entiers:
np.random.randint(0,10,(3,3))

array([[6, 6, 8],
       [6, 7, 9],
       [2, 4, 6]])

<div class="alert alert-danger">
<b>les commandes et codes à apprendre par cœur </b></div>

<div class="alert alert-danger">
<h3>Exercises</h3>
</div>

<div class="alert alert-success">
<ul> <b>veuillez écrire les réponses à ces questions:</b>
<li> Qu'est-ce qu'un entier ?
<li> Qu'est-ce qu'une chaîne ?
<li> Quelle est la différence entre un entier et une flottant?
<li> Qu'est-ce qu'une liste ?
<li> Quels sont les avantages d'un tuple ?
<li> Comment transformer une colonne pandas en liste ?
<li> Comment extraire la valeur de la liste située en position 10 ?
<li> Quelles sont les méthodes pour définir les variables ?
<li> Comment vérifier le type d'une variable ?
<li> Comment ajouter une variable à un tuple ?
<li> Comment envoyer toutes les valeurs d'une trame de données à une liste ?
<li> Comment créer une trame de données à partir d'une liste ?
<li> Comment accéder à une lettre dans une chaîne à une certaine position ?
<li> Comment définir plusieurs variables en même temps ?
<li> Définir une flottante
<li> Initialisez deux entiers : a = 0 et b = 10 
<li> Créer la liste : liste =[17, 38, 10, 25, 72]
<li> Inversez et affichez la liste
<li> Affichez l’indice de l’élément 17
<li> Affichez la sous-liste du 2e au 3e élément
<li> Affichez la sous-liste du début au 2e élément
<li> Affichez la sous-liste du 3e élément à la fin de la liste 
<li> Affichez la sous-liste complète de la liste
<li> Affichez le dernier élément en utilisant un indiçage négatif
<li>Créez un tableau numpy 1D de int de 0 à 9
    </ul>
</div>

<div class="alert alert-success">
<li> Créer une liste
<li> ajouter une chaîne, un entier et un flottant à la liste
<li> ajouter la liste à 'key5' dans le dictionnaire
<li> temps pour résoudre - 2 minutes </div>

<div class="alert alert-success">
<li> créer une trame de données à l'aide du dictionnaire:
<li> d1 = {'Subj_ID': '001', 'score': 16, 'group' : 2, 'condition': 'cognition'}
<li> résoudre l'erreur en utilisant l'Internet
<li> temps pour résoudre - 2 minutes
</div>

<div class="alert alert-success">
<li> la commande ls_fruits[::2] qu'est ce que ça fait ?
</div>

In [65]:
ls_fruits = ['pomme','banane','orange','poire','raisins']
ls_fruits[::3]

['pomme', 'poire']

In [66]:
# Créez un cadre de données de pandas
# à partir de chacun des éléments ci-dessous:

list('abcedfghijklmnopqrstuvwxyz')

np.arange(26)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])